"""initial_schema

Revision ID: 5701fe81df0d
Revises: 
Create Date: 2026-05-14 00:38:35.503847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5701fe81df0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_number_sequences',
    sa.Column('year_yy', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year_yy', 'employee_number')
    )
    op.create_table('stamp_tax_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'member', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendor_price_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_spec', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('quoted_at', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('scan', 'manual', name='vendorpricehistorysource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_name_kana', sa.String(length=200), nullable=True),
    sa.Column('primary_work_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('bank_info', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_number', sa.String(length=20), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_location', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('original_client_name', sa.String(length=255), nullable=True),
    sa.Column('period_quote_start', sa.Date(), nullable=True),
    sa.Column('period_quote_end', sa.Date(), nullable=True),
    sa.Column('period_contract_start', sa.Date(), nullable=True),
    sa.Column('period_contract_end', sa.Date(), nullable=True),
    sa.Column('period_actual_start', sa.Date(), nullable=True),
    sa.Column('period_actual_end', sa.Date(), nullable=True),
    sa.Column('order_type', sa.Enum('private', 'government', name='ordertype'), nullable=True),
    sa.Column('contract_type', sa.Enum('prime', 'sub', name='contracttype'), nullable=True),
    sa.Column('awarding_type', sa.Enum('special', 'competitive', name='awardingtype'), nullable=True),
    sa.Column('payment_condition', sa.Text(), nullable=True),
    sa.Column('project_summary', sa.Text(), nullable=True),
    sa.Column('prev_construction_type', sa.Enum('own', 'other', 'none', name='prevconstructiontype'), nullable=True),
    sa.Column('prev_construction_year', sa.Integer(), nullable=True),
    sa.Column('prev_construction_other', sa.String(length=255), nullable=True),
    sa.Column('client_contact_company', sa.String(length=255), nullable=True),
    sa.Column('client_contact_person', sa.String(length=100), nullable=True),
    sa.Column('client_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('sales_person_id', sa.UUID(), nullable=True),
    sa.Column('construction_person_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('project_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('status', sa.Enum('quote', 'ordered', 'started', 'in_progress', 'completed', 'billed', 'paid', name='projectstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['construction_person_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sales_person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_number')
    )
    op.create_table('edit_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_type', sa.Enum('create', 'update', 'delete', name='edithistorychangetype'), nullable=False),
    sa.Column('field_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('previous_balance', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('outstanding_balance', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('current_purchase', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('client_address', sa.String(length=255), nullable=True),
    sa.Column('client_company', sa.String(length=255), nullable=True),
    sa.Column('client_person', sa.String(length=100), nullable=True),
    sa.Column('amount_excl_tax', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('construction_period_start', sa.Date(), nullable=True),
    sa.Column('construction_period_end', sa.Date(), nullable=True),
    sa.Column('payment_condition', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('stamp_tax', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', 'signed_returned', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logged_by', sa.UUID(), nullable=False),
    sa.Column('log_type', sa.Enum('text', 'photo', 'drawing', 'milestone', name='progresslogtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status_changed_to', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qcds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('spare_cost', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('industrial_waste_cost', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('labor_insurance_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('construction_insurance_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('special_insurance_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('office_supplies', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('communication_cost', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('misc_cost', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('site_staff_salary_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('common_overhead_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('shared_overhead_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('general_admin_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('target_operating_profit_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('actual_site_personnel_cost', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('project_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('project_location_snapshot', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('payment_condition', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('person_in_charge_id', sa.UUID(), nullable=True),
    sa.Column('conditions_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', name='quotestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_in_charge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('original_file_path', sa.String(length=500), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'image', 'excel', name='scanjobfiletype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'succeeded', 'failed', 'reviewed', name='scanjobstatus'), nullable=False),
    sa.Column('gemini_model', sa.String(length=100), nullable=True),
    sa.Column('gemini_response_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('progress_log_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('canon_sync_status', sa.Enum('local_only', 'syncing', 'synced', name='canonsyncstatus'), nullable=False),
    sa.Column('canon_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['progress_log_id'], ['progress_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qcds_direct_works',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qcds_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('vendor_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('subcontract', 'material', 'other', name='qcdscategory'), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('agreed_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('settlement_amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('agreement_checked', sa.Boolean(), nullable=False),
    sa.Column('payment_month_4', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_5', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_6', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_7', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_8', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_9', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_10', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_11', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_12', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_1', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_2', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_month_3', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('payment_completed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['qcds_id'], ['qcds.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('source_vendor_id', sa.UUID(), nullable=True),
    sa.Column('source_scan_result_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['source_vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name_detected', sa.String(length=200), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('quoted_date_detected', sa.Date(), nullable=True),
    sa.Column('subtotal_detected', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('tax_detected', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('total_detected', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_result_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_result_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('applied_to_qcds', sa.Boolean(), nullable=False),
    sa.Column('applied_to_quote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_result_items')
    op.drop_table('scan_results')
    op.drop_table('quote_items')
    op.drop_table('qcds_direct_works')
    op.drop_table('progress_attachments')
    op.drop_table('invoice_items')
    op.drop_table('scan_jobs')
    op.drop_table('quotes')
    op.drop_table('qcds')
    op.drop_table('progress_logs')
    op.drop_table('orders')
    op.drop_table('invoices')
    op.drop_table('edit_histories')
    op.drop_table('projects')
    op.drop_table('vendors')
    op.drop_table('vendor_price_histories')
    op.drop_table('users')
    op.drop_table('stamp_tax_table')
    op.drop_table('project_number_sequences')
    # ### end Alembic commands ###
